export enum taskEnumReducer {
  REMOVE_TASK = 'TODOLIST/TASK_REDUCER/REMOVE_TASK',
  ADD_TASK = 'TODOLIST/TASK_REDUCER/ADD_TASK',
  UPDATE_TASK = 'TODOLIST/TASK_REDUCER/UPDATE_TASK',
  SET_TASKS = 'TODOLIST/TASK_REDUCER/SET-TASKS',
}
