export enum todolistEnumReducer {
  REMOVE_TODOLIST = 'TODOLIST/TODOLIST_REDUCER/REMOVE-TODOLIST',
  ADD_TODOLIST = 'TODOLIST/TODOLIST_REDUCER/ADD_TODOLIST',
  CHANGE_TODOLIST_TITLE = 'TODOLIST/TODOLIST_REDUCER/CHANGE-TODOLIST-TITLE',
  CHANGE_TODOLIST_FILTER = 'TODOLIST/TODOLIST_REDUCER/CHANGE_TODOLIST_FILTER',
  CHANGE_TODOLIST_ENTITY_STATUS = 'TODOLIST/TODOLIST_REDUCER/CHANGE_TODOLIST_ENTITY_STATUS',
  SET_TODOS = 'TODOLIST/TODOLIST_REDUCER/SET_TODOS',
}
